// figma-forge importer plugin
// Writes W3C DTCG-shaped tokens into Figma Variables + paint/text/effect styles.
// All token data is embedded into TOKENS_DTCG at bundle time.
// This file is generated by figma-forge; do not edit manually.

// ============================================================================
// EMBEDDED TOKEN PAYLOAD (overwritten at bundle time by figma-forge)
// ============================================================================
const TOKENS_DTCG: any = /* __FIGMA_FORGE_EMBEDDED_TOKENS__ */ {};

// ============================================================================
// PLUGIN ENTRY
// ============================================================================

figma.showUI(__html__, { width: 420, height: 640 });

figma.ui.onmessage = async (msg: { type: string; payload?: any }) => {
  if (msg.type === "run-import") {
    try {
      const stats = await runImport(TOKENS_DTCG);
      figma.ui.postMessage({ type: "import-complete", stats });
    } catch (err: any) {
      figma.ui.postMessage({ type: "import-failed", error: String(err && err.message ? err.message : err) });
    }
  } else if (msg.type === "close") {
    figma.closePlugin();
  }
};

// ============================================================================
// MAIN IMPORT LOGIC
// ============================================================================

interface ImportStats {
  collectionsCreated: number;
  modesCreated: number;
  variablesCreated: number;
  paintStylesCreated: number;
  textStylesCreated: number;
  effectStylesCreated: number;
  warnings: string[];
  errors: string[];
  durationMs: number;
}

async function runImport(dtcg: any): Promise<ImportStats> {
  const startedAt = Date.now();
  const stats: ImportStats = {
    collectionsCreated: 0,
    modesCreated: 0,
    variablesCreated: 0,
    paintStylesCreated: 0,
    textStylesCreated: 0,
    effectStylesCreated: 0,
    warnings: [],
    errors: [],
    durationMs: 0
  };

  // Topological sort: primitives first, then semantic aliases, then composites.
  const groups = inferCollectionGroups(dtcg);
  const variableCache = new Map<string, Variable>();

  // Pass 1 — primitive variables
  for (const groupName of ["color.primitive", "dimension", "font"]) {
    const groupData = getByPath(dtcg, groupName);
    if (!groupData) continue;
    const collection = figma.variables.createVariableCollection(humanize(groupName));
    stats.collectionsCreated++;
    const modeId = collection.modes[0].modeId;
    walkAndCreate(groupData, groupName, collection, modeId, variableCache, stats);
  }

  // Pass 2 — semantic aliases (with mode handling)
  const semantic = getByPath(dtcg, "color.semantic");
  if (semantic) {
    const collection = figma.variables.createVariableCollection("Semantic — Color");
    stats.collectionsCreated++;
    const lightMode = collection.modes[0].modeId;
    let darkMode: string | null = null;
    if (hasModeKeys(semantic)) {
      collection.renameMode(lightMode, "Light");
      darkMode = collection.addMode("Dark");
      stats.modesCreated += 2;
    }
    walkAndCreateSemantic(semantic, "color.semantic", collection, lightMode, darkMode, variableCache, stats);
  }

  // Pass 3 — typography text styles
  const typography = getByPath(dtcg, "typography");
  if (typography) {
    await createTextStyles(typography, "typography", variableCache, stats);
  }

  // Pass 4 — shadow effect styles
  const shadows = getByPath(dtcg, "shadow");
  if (shadows) {
    createEffectStyles(shadows, "shadow", stats);
  }

  // Pass 5 — paint styles bound to semantic variables
  if (semantic) {
    createPaintStyles(semantic, "color.semantic", variableCache, stats);
  }

  stats.durationMs = Date.now() - startedAt;
  return stats;
}

// ============================================================================
// VARIABLE CREATION
// ============================================================================

function walkAndCreate(
  node: any,
  pathPrefix: string,
  collection: VariableCollection,
  modeId: string,
  cache: Map<string, Variable>,
  stats: ImportStats
): void {
  if (isLeaf(node)) {
    const variable = createVariableFromLeaf(node, pathPrefix, collection, modeId, cache, stats);
    if (variable) cache.set(pathPrefix, variable);
    return;
  }
  for (const key of Object.keys(node)) {
    if (key.startsWith("$")) continue;
    walkAndCreate(node[key], `${pathPrefix}.${key}`, collection, modeId, cache, stats);
  }
}

function walkAndCreateSemantic(
  node: any,
  pathPrefix: string,
  collection: VariableCollection,
  lightMode: string,
  darkMode: string | null,
  cache: Map<string, Variable>,
  stats: ImportStats
): void {
  if (isLeaf(node)) {
    const variable = createSemanticVariable(node, pathPrefix, collection, lightMode, darkMode, cache, stats);
    if (variable) cache.set(pathPrefix, variable);
    return;
  }
  for (const key of Object.keys(node)) {
    if (key.startsWith("$")) continue;
    walkAndCreateSemantic(node[key], `${pathPrefix}.${key}`, collection, lightMode, darkMode, cache, stats);
  }
}

function createVariableFromLeaf(
  leaf: any,
  path: string,
  collection: VariableCollection,
  modeId: string,
  cache: Map<string, Variable>,
  stats: ImportStats
): Variable | null {
  const type = leaf.$type;
  const figmaType = mapTypeToFigma(type);
  if (figmaType === null) {
    stats.warnings.push(`Skipped ${path}: type "${type}" has no native Figma variable mapping (saved as metadata only).`);
    return null;
  }
  const variable = figma.variables.createVariable(figmaPath(path), collection, figmaType);
  const value = resolveValue(leaf.$value, cache, stats);
  variable.setValueForMode(modeId, value as VariableValue);
  if (leaf.$description) variable.description = leaf.$description;
  stats.variablesCreated++;
  return variable;
}

function createSemanticVariable(
  leaf: any,
  path: string,
  collection: VariableCollection,
  lightMode: string,
  darkMode: string | null,
  cache: Map<string, Variable>,
  stats: ImportStats
): Variable | null {
  const type = leaf.$type;
  const figmaType = mapTypeToFigma(type);
  if (figmaType === null) return null;
  const variable = figma.variables.createVariable(figmaPath(path), collection, figmaType);
  const value = leaf.$value;
  if (typeof value === "object" && !Array.isArray(value) && ("light" in value || "dark" in value)) {
    if ("light" in value) variable.setValueForMode(lightMode, resolveValue(value.light, cache, stats) as VariableValue);
    if (darkMode && "dark" in value) variable.setValueForMode(darkMode, resolveValue(value.dark, cache, stats) as VariableValue);
  } else {
    variable.setValueForMode(lightMode, resolveValue(value, cache, stats) as VariableValue);
  }
  if (leaf.$description) variable.description = leaf.$description;
  stats.variablesCreated++;
  return variable;
}

// ============================================================================
// VALUE RESOLUTION
// ============================================================================

function resolveValue(raw: any, cache: Map<string, Variable>, stats: ImportStats): any {
  if (typeof raw === "string") {
    // Alias reference: "{path.to.token}"
    const aliasMatch = raw.match(/^\{([\w.\-]+)\}$/);
    if (aliasMatch) {
      const target = cache.get(aliasMatch[1]);
      if (target) return figma.variables.createVariableAlias(target);
      stats.warnings.push(`Alias ${raw} unresolved at resolution time; deferring to literal.`);
      return raw;
    }
    // Hex color
    if (/^#[0-9A-Fa-f]{3,8}$/.test(raw)) return hexToRGBA(raw);
    // Dimension with unit
    const dimMatch = raw.match(/^(-?[\d.]+)(px|rem|em)?$/);
    if (dimMatch) {
      const n = parseFloat(dimMatch[1]);
      const unit = dimMatch[2] || "px";
      return unit === "rem" ? n * 16 : unit === "em" ? n * 16 : n;
    }
    return raw;
  }
  if (typeof raw === "number" || typeof raw === "boolean") return raw;
  return raw;
}

function hexToRGBA(hex: string): RGBA {
  const clean = hex.replace("#", "");
  const n = clean.length;
  let r = 0, g = 0, b = 0, a = 1;
  if (n === 3) { r = parseInt(clean[0] + clean[0], 16); g = parseInt(clean[1] + clean[1], 16); b = parseInt(clean[2] + clean[2], 16); }
  else if (n === 6) { r = parseInt(clean.slice(0, 2), 16); g = parseInt(clean.slice(2, 4), 16); b = parseInt(clean.slice(4, 6), 16); }
  else if (n === 8) { r = parseInt(clean.slice(0, 2), 16); g = parseInt(clean.slice(2, 4), 16); b = parseInt(clean.slice(4, 6), 16); a = parseInt(clean.slice(6, 8), 16) / 255; }
  return { r: r / 255, g: g / 255, b: b / 255, a };
}

// ============================================================================
// TEXT STYLE CREATION
// ============================================================================

async function createTextStyles(node: any, pathPrefix: string, cache: Map<string, Variable>, stats: ImportStats): Promise<void> {
  if (isLeaf(node) && node.$type === "typography") {
    const v = node.$value;
    const family = resolveStringValue(v.fontFamily, cache);
    const weight = resolveNumericValue(v.fontWeight, cache);
    const fontName = { family, style: weightToStyle(weight) };
    try {
      await figma.loadFontAsync(fontName);
    } catch (e) {
      stats.warnings.push(`Font not installed: ${family} ${fontName.style}; using fallback.`);
      fontName.family = "Inter";
      await figma.loadFontAsync(fontName);
    }
    const style = figma.createTextStyle();
    style.name = figmaPath(pathPrefix);
    style.fontName = fontName;
    style.fontSize = resolveNumericValue(v.fontSize, cache);
    if (v.lineHeight !== undefined) {
      const lh = resolveNumericValue(v.lineHeight, cache);
      style.lineHeight = lh > 4 ? { value: lh, unit: "PIXELS" } : { value: lh * 100, unit: "PERCENT" };
    }
    if (v.letterSpacing !== undefined) {
      style.letterSpacing = { value: resolveNumericValue(v.letterSpacing, cache), unit: "PIXELS" };
    }
    if (node.$description) style.description = node.$description;
    stats.textStylesCreated++;
    return;
  }
  for (const key of Object.keys(node)) {
    if (key.startsWith("$")) continue;
    await createTextStyles(node[key], `${pathPrefix}.${key}`, cache, stats);
  }
}

// ============================================================================
// EFFECT STYLE CREATION (shadows)
// ============================================================================

function createEffectStyles(node: any, pathPrefix: string, stats: ImportStats): void {
  if (isLeaf(node) && node.$type === "shadow") {
    const shadows = Array.isArray(node.$value) ? node.$value : [node.$value];
    const style = figma.createEffectStyle();
    style.name = figmaPath(pathPrefix);
    style.effects = shadows.map((s: any) => ({
      type: "DROP_SHADOW" as const,
      visible: true,
      color: hexToRGBA(s.color),
      offset: { x: parseFloat(s.offsetX), y: parseFloat(s.offsetY) },
      radius: parseFloat(s.blur),
      spread: parseFloat(s.spread || "0px"),
      blendMode: "NORMAL" as BlendMode
    }));
    if (node.$description) style.description = node.$description;
    stats.effectStylesCreated++;
    return;
  }
  for (const key of Object.keys(node)) {
    if (key.startsWith("$")) continue;
    createEffectStyles(node[key], `${pathPrefix}.${key}`, stats);
  }
}

// ============================================================================
// PAINT STYLE CREATION (bound to variables)
// ============================================================================

function createPaintStyles(node: any, pathPrefix: string, cache: Map<string, Variable>, stats: ImportStats): void {
  if (isLeaf(node) && node.$type === "color") {
    const variable = cache.get(pathPrefix);
    if (!variable) {
      stats.warnings.push(`No variable found for paint style ${pathPrefix}; skipped.`);
      return;
    }
    const style = figma.createPaintStyle();
    style.name = figmaPath(pathPrefix);
    const basePaint: SolidPaint = { type: "SOLID", color: { r: 0, g: 0, b: 0 }, opacity: 1 };
    const boundPaint = figma.variables.setBoundVariableForPaint(basePaint, "color", variable);
    style.paints = [boundPaint];
    if (node.$description) style.description = node.$description;
    stats.paintStylesCreated++;
    return;
  }
  for (const key of Object.keys(node)) {
    if (key.startsWith("$")) continue;
    createPaintStyles(node[key], `${pathPrefix}.${key}`, cache, stats);
  }
}

// ============================================================================
// UTILITIES
// ============================================================================

function isLeaf(node: any): boolean {
  return node && typeof node === "object" && ("$value" in node);
}

function hasModeKeys(node: any): boolean {
  return JSON.stringify(node).includes('"light"') || JSON.stringify(node).includes('"dark"');
}

function getByPath(obj: any, dottedPath: string): any {
  return dottedPath.split(".").reduce((acc, k) => (acc == null ? undefined : acc[k]), obj);
}

function figmaPath(dottedPath: string): string {
  return dottedPath.replace(/\./g, "/");
}

function humanize(dottedPath: string): string {
  return dottedPath.split(".").map(s => s[0].toUpperCase() + s.slice(1)).join(" — ");
}

function mapTypeToFigma(dtcgType: string): "COLOR" | "FLOAT" | "STRING" | "BOOLEAN" | null {
  switch (dtcgType) {
    case "color":      return "COLOR";
    case "dimension":  return "FLOAT";
    case "number":     return "FLOAT";
    case "fontWeight": return "FLOAT";
    case "fontFamily": return "STRING";
    case "string":     return "STRING";
    case "boolean":    return "BOOLEAN";
    case "duration":   return null;
    case "cubicBezier": return null;
    case "shadow":     return null;
    case "typography": return null;
    case "gradient":   return null;
    default:           return null;
  }
}

function inferCollectionGroups(_dtcg: any): string[] {
  return ["color.primitive", "color.semantic", "dimension", "font"];
}

function resolveStringValue(v: any, cache: Map<string, Variable>): string {
  if (typeof v === "string") {
    const m = v.match(/^\{([\w.\-]+)\}$/);
    if (m && cache.has(m[1])) {
      const variable = cache.get(m[1])!;
      const defaultModeId = variable.variableCollectionId;
      // Best-effort literal extraction; the alias remains the binding in production
      return v.replace(/^\{|\}$/g, "").split(".").pop()!;
    }
    return v;
  }
  return String(v);
}

function resolveNumericValue(v: any, cache: Map<string, Variable>): number {
  if (typeof v === "number") return v;
  if (typeof v === "string") {
    const m = v.match(/^(-?[\d.]+)/);
    if (m) return parseFloat(m[1]);
  }
  return 0;
}

function weightToStyle(weight: number): string {
  if (weight <= 100) return "Thin";
  if (weight <= 200) return "ExtraLight";
  if (weight <= 300) return "Light";
  if (weight <= 400) return "Regular";
  if (weight <= 500) return "Medium";
  if (weight <= 600) return "SemiBold";
  if (weight <= 700) return "Bold";
  if (weight <= 800) return "ExtraBold";
  return "Black";
}
